// utilities
import cx from 'classnames'
import type { Metadata } from 'next'

// fonts
import { nunito } from './fonts'

// styles
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode
}>) => {
  return (
    <html lang="en">
      <body
        className={cx(
          nunito.variable,
          'min-h-screen',
          'bg-gradient-primary',
          'backdrop-blur-3xl'
        )}
      >
        {children}
      </body>
    </html>
  )
}

export default RootLayout
